services:
  - name: movie-downloader-backend
    type: web
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: persistent-data
      size: 1GB
    healthCheckPath: /
    runtime:
      - nodejs: 16
    staticPublish:
      directory: public
